name: pagseguro_smart_flutter
description: A new Flutter plugin.
version: 0.0.1
homepage: https://gabul.dev
repository: https://github.com/gabuldev/pagseguro_smart_flutter

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.gabul.pagseguro_smart_flutter
        pluginClass: PagseguroSmartFlutterPlugin
      ios:
        pluginClass: PagseguroSmartFlutterPlugin
